---
- name: install postfix
  yum:
    name: postfix
    state: present
  notify: restart postfix

- name: install mail client util
  yum:
    name: mailx
    state: present

- name: copy postfix config file
  template:
    src: templates/etc/postfix/main.cf
    dest: /etc/postfix/main.cf
  notify: restart postfix
...
